name: pass-deposit-services Continuous Integration
on:
  pull_request:
  workflow_dispatch:
#  schedule:
#    - cron: '0 3 * * *' # daily, at 3am

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  print-workflow-description:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This is a CI build of branch ${{ github.ref }} in repository ${{ github.repository }}"
      - run: echo "This job was triggered by a ${{ github.event_name }} event and is running on a ${{ runner.os }} server"

  pom-workaround:
    name: "Run Parent POM Workaround"
    runs-on: ubuntu-latest
    steps:
      - name: "Parent POM Workaround: Checkout pass 'main'"
        uses: actions/checkout@v2
        with:
          repository: eclipse-pass/main
      - name: "Set up JDK 11"
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: "Cache Maven packages"
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: "Parent POM Workaround: Install from pass 'main'"
        run: mvn install --file pom.xml

  run-tests:
    name: "Run Unit & Integration Tests"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout the repository"
        uses: actions/checkout@v2
      - name: "Set up JDK 11"
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: "Cache Maven packages"
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: "Run unit & integration tests"
        run: mvn -B verify --file pom.xml
